name: Swift CI

on:
  push:
    branches:
      - master
      - '!gh-pages'
    paths:
      - '*.podspec'
      - 'Gemfile*'
      - 'Package.swift'
      - 'swift/**'
      - '.github/workflows/swift.yaml'
      - '.buildscript/build_swift_docs.sh'
  pull_request:
    paths:
      - '*.podspec'
      - 'Gemfile*'
      - 'Package.swift'
      - 'swift/**'
      - '.github/workflows/swift.yaml'
      - '.buildscript/build_swift_docs.sh'

jobs:
  development-apps:
    runs-on: macos-latest

    strategy:
      matrix:
        scheme: 
        - Development-Unit-WorkflowTests
        - Development-Unit-WorkflowUITests
        - Development-Unit-SplitScreenTests
        - Development-Unit-TabBarScreenTests
        - Development-Unit-TicTacToeTests

    steps:
    - uses: actions/checkout@v1

    - name: Cache gems
      uses: actions/cache@v1
      with:
          path: .bundle
          key: gems-${{ hashFiles('Gemfile.lock') }}

    - name: Bundle Install
      run: |
        bundle check || bundle install --path .bundle

    - name: Pod Install
      run: |
        bundle exec pod gen Development.podspec

    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.4.app

    - name: Build & Test
      run: |
        set -o pipefail && xcodebuild -workspace gen/Development/Development.xcworkspace -scheme ${{ matrix.scheme }} -destination platform\=iOS\ Simulator,OS\=13.4,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty

  spm:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Swift Package Manager - iOS
      run: |
        xcodebuild -scheme "Workflow-Package" test -destination "name=iPhone 11"

    - name: Swift Package Manager - macOS
      run: |
        xcodebuild -scheme "Workflow-Package" test

  tutorial:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache gems
      uses: actions/cache@v1
      with:
          path: .bundle
          key: gems-${{ hashFiles('Gemfile.lock') }}

    - name: Bundle Install
      run: |
        bundle check || bundle install --path .bundle

    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.4.app

    - name: Tutorial App
      run: |
        cd swift/Samples/Tutorial
        bundle exec pod install
        set -o pipefail && xcodebuild -workspace Tutorial.xcworkspace -scheme Tutorial -destination platform\=iOS\ Simulator,OS\=13.4,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty

  documentation-lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache gems
      uses: actions/cache@v1
      with:
          path: .bundle
          key: gems-${{ hashFiles('Gemfile.lock') }}

    - name: Bundle Install
      run: |
        bundle check || bundle install --path .bundle
        brew install sourcedocs
        
    - name: Swiftdocs
      run: |
        .buildscript/build_swift_docs.sh ${{ runner.temp }}/swiftdocs